/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;


public class AboutView extends javax.swing.JPanel {

    /**
     * Creates new form AboutView
     */
    public AboutView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panal = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        TopicName = new javax.swing.JLabel();
        ProjectName = new javax.swing.JLabel();
        GrName = new javax.swing.JLabel();
        NameLeader = new javax.swing.JLabel();
        MemberName = new javax.swing.JLabel();
        NameMember = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1008, 680));
        setLayout(new java.awt.BorderLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        TopicName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TopicName.setForeground(new java.awt.Color(255, 0, 0));
        TopicName.setText("Phần mềm quản lý cửa hàng trà sữa");

        ProjectName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ProjectName.setForeground(new java.awt.Color(0, 0, 255));
        ProjectName.setText("Đề tài môn lập trình java");

        GrName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GrName.setText("Nhóm 10:");

        NameLeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLeader.setForeground(new java.awt.Color(0, 128, 0));
        NameLeader.setText("Trần Thanh Tuấn - 20DH111009");

        MemberName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MemberName.setForeground(new java.awt.Color(0, 128, 0));
        MemberName.setText("Lê Hoàng Phúc - 20DH112149");

        NameMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameMember.setForeground(new java.awt.Color(0, 128, 0));
        NameMember.setText("Hà Vĩnh Tài - 20DH110589");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLeader)
                    .addComponent(GrName)
                    .addComponent(ProjectName)
                    .addComponent(TopicName)
                    .addComponent(NameMember)
                    .addComponent(MemberName))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(TopicName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProjectName)
                .addGap(18, 18, 18)
                .addComponent(GrName)
                .addGap(27, 27, 27)
                .addComponent(NameLeader)
                .addGap(18, 18, 18)
                .addComponent(NameMember)
                .addGap(18, 18, 18)
                .addComponent(MemberName)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanalLayout = new javax.swing.GroupLayout(Panal);
        Panal.setLayout(PanalLayout);
        PanalLayout.setHorizontalGroup(
            PanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        PanalLayout.setVerticalGroup(
            PanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(Panal, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel GrName;
    private javax.swing.JLabel MemberName;
    private javax.swing.JLabel NameLeader;
    private javax.swing.JLabel NameMember;
    private javax.swing.JPanel Panal;
    private javax.swing.JLabel ProjectName;
    private javax.swing.JLabel TopicName;
    // End of variables declaration//GEN-END:variables
}
