package views.admin;

import utils.RandomColor;


public class HomeView extends javax.swing.JPanel {

    private boolean isShowLed = false;

    public static void setTimeout(Runnable runnable, int delay) {
        new Thread(() -> {
            try {
                Thread.sleep(delay);
                runnable.run();
            } catch (Exception e) {
                System.err.println(e);
            }
        }).start();
    }

    public HomeView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labLogo = new javax.swing.JLabel();
        Br = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1008, 680));
        setMinimumSize(new java.awt.Dimension(1008, 680));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotrasua.png"))); // NOI18N
        labLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labLogo.setMaximumSize(new java.awt.Dimension(400, 400));
        labLogo.setMinimumSize(new java.awt.Dimension(400, 400));
        labLogo.setPreferredSize(new java.awt.Dimension(400, 400));
        add(labLogo);
        labLogo.setBounds(560, -10, 440, 400);

        Br.setBackground(new java.awt.Color(153, 255, 255));
        Br.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Br.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brtrasua.jpg"))); // NOI18N
        Br.setToolTipText("");
        Br.setMinimumSize(new java.awt.Dimension(1008, 680));
        Br.setPreferredSize(new java.awt.Dimension(1008, 680));
        add(Br);
        Br.setBounds(-420, -210, 1920, 1080);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        isShowLed = !isShowLed;
        makeLed();
    }//GEN-LAST:event_formMousePressed

    private void makeLed() {
        if (!isShowLed) {
            return;
        }
        setBackground(RandomColor.getColor());
        Br.setForeground(RandomColor.getContrastColor(getBackground()));
        setTimeout(this::makeLed, 200);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Br;
    private javax.swing.JLabel labLogo;
    // End of variables declaration//GEN-END:variables
}
